waypoints: [
{
  id: 1, #point 1
  pose: {
    point: [
      1.0, #x,
      2.0, #y,
      3.0, #z,
    ],
    orientation: [
      1.0, #x
      2.0, #y
      3.0, #z
      4.0, #w
    ]
  }
},
{
  id: 2, #point 2
  pose: {
    point: [
      1.0, #x,
      2.0, #y,
      3.0, #z,
    ],
    orientation: [
      1.0, #x
      2.0, #y
      3.0, #z
      4.0, #w
    ]
  }
},
]